_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_BOX_HEAD:
    RES5HALVE: False
    POOLER_TYPE: "ROIPool"
    ATTR: True
    NUM_ATTRS: 80
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
